package jena1;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.jena.riot.RDFFormat;
import org.json.JSONException;

public class interfaz extends javax.swing.JFrame {
    private Jena1 aemet;
    private grafo grafo = new grafo();
    public interfaz() {
        
        aemet = new Jena1();
        try {
            grafo = aemet.creaGrafo();
        } catch (IOException | JSONException ex) {
            Logger.getLogger(interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        turtle.setSelected(true);
        jTextArea1.setText(grafo.tripletas(RDFFormat.TURTLE_PRETTY));
        jTextArea1.setCaretPosition(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        rdf = new javax.swing.JRadioButton();
        ntriple = new javax.swing.JRadioButton();
        turtle = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        buttonGroup1.add(rdf);
        rdf.setText("RDF/XML");
        rdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdfActionPerformed(evt);
            }
        });

        buttonGroup1.add(ntriple);
        ntriple.setText("N-Triple");
        ntriple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntripleActionPerformed(evt);
            }
        });

        buttonGroup1.add(turtle);
        turtle.setText("Turtle");
        turtle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turtleActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Guardado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(turtle)
                .addGap(57, 57, 57)
                .addComponent(rdf)
                .addGap(61, 61, 61)
                .addComponent(ntriple)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdf)
                    .addComponent(ntriple)
                    .addComponent(turtle)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdfActionPerformed
        jTextArea1.setText(grafo.tripletas(RDFFormat.RDFXML_PRETTY));
        jTextArea1.setCaretPosition(0);
    }//GEN-LAST:event_rdfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre ="";
        String extension="";
        
        if (turtle.isSelected()) {
            nombre = grafo.tripletas(RDFFormat.TURTLE_PRETTY);
            extension = ".ttl";
        } else if (rdf.isSelected()) {
            nombre = grafo.tripletas(RDFFormat.RDFXML_PRETTY);
            extension = ".rdf";
        } else if (ntriple.isSelected()) {
            nombre = grafo.tripletas(RDFFormat.NTRIPLES);
            extension = ".nt";
        } 
        
        String ruta = guardado();
        if (ruta != null) {
            BufferedWriter writer = null;
            try {
                writer = new BufferedWriter( new FileWriter( ruta + extension ));
                writer.write(nombre);
            } catch ( IOException e) {
            } finally {
                try {
                    if ( writer != null)
                    writer.close();
                    JOptionPane.showMessageDialog(null, "El archivo ha sido guardado",
                                                "Guardado", JOptionPane.INFORMATION_MESSAGE);
                }
                catch ( IOException e){
                }
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Han habido problemas.",
                                                "Destino incorrecto", JOptionPane.INFORMATION_MESSAGE);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void turtleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turtleActionPerformed
        jTextArea1.setText(grafo.tripletas(RDFFormat.TURTLE_PRETTY));
        jTextArea1.setCaretPosition(0);
    }//GEN-LAST:event_turtleActionPerformed

    private void ntripleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntripleActionPerformed
        jTextArea1.setText(grafo.tripletas(RDFFormat.NTRIPLES));
        jTextArea1.setCaretPosition(0);
    }//GEN-LAST:event_ntripleActionPerformed

    private String guardado() {
        JFileChooser fc = new JFileChooser(".");
        FileNameExtensionFilter filtro;
        filtro = new FileNameExtensionFilter("Archivos;","ttl","rdf","nt");
        fc.addChoosableFileFilter(filtro);
        fc.setAcceptAllFileFilterUsed(false);
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        int res = fc.showSaveDialog(null);

        if (res == JFileChooser.APPROVE_OPTION) {
            return fc.getSelectedFile().getPath();        
        }
        return null; 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton ntriple;
    private javax.swing.JRadioButton rdf;
    private javax.swing.JRadioButton turtle;
    // End of variables declaration//GEN-END:variables
}
